#include "ef.h"
#include "ef-test.h"
#include "catch_single_include.hxx"

// These tests deliberately drive every name##_free path generated by
// GEN_ALLOC_CLONE_FREE. Under UBSan -fsanitize=function this catches any
// future regression where the destructor signature stops matching the
// indirect-call type used by name##_free (the bug fixed by inlining the
// macro body to call name##_destruct directly).

TEST_CASE("field_free dispatches to field_destruct", "[alloc-free]") {
    field_t *f = field_alloc();
    REQUIRE(f != nullptr);
    field_free(f);
    field_free(nullptr);  // null-tolerant
}

TEST_CASE("hdr_free dispatches to hdr_destruct", "[alloc-free]") {
    hdr_t *h = hdr_alloc();
    REQUIRE(h != nullptr);
    hdr_free(h);
    hdr_free(nullptr);
}

TEST_CASE("frame_free dispatches to frame_destruct", "[alloc-free]") {
    frame_t *f = frame_alloc();
    REQUIRE(f != nullptr);
    frame_free(f);
    frame_free(nullptr);
}

TEST_CASE("frame_free of a populated frame releases the stack", "[alloc-free]") {
    // Exercises the recursive hdr_free -> field_free chain so UBSan also
    // sees the indirect calls via the cloned templates' destructors.
    frame_t *f = parse_frame_wrap({"eth", "dmac", "00:00:00:00:00:01",
                                   "smac", "00:00:00:00:00:02"});
    REQUIRE(f != nullptr);
    frame_free(f);
}
